### ISSUE TITLE
About why SPCS_Net is passed

### ISSUE THREAD

**Issue by dbqwcx123** [chenkang455/Spike-Zoo#1]
I'm wondering why the SPCS_Net model has been passed, is it temporarily not available for public release?

**Comment by chenkang455** [comment]
> I'm wondering why the SPCS_Net model has been passed, is it temporarily not available for public release?

Yes， SPCS-Net is under review, we will release its code once the manuscript is accepted.

**Comment by dbqwcx123** [comment]
> > I'm wondering why the SPCS_Net model has been passed, is it temporarily not available for public release?
> 
> Yes， SPCS-Net is under review, we will release its code once the manuscript is accepted.

OK, I see, thanks for replying!
